import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../../presentation/screens/owner/reports/reports_data.dart';
import '../../domain/entities/report_range.dart';

class PdfGeneratorService {
  
  /// Generates a Rent Receipt PDF and returns the bytes.
  Future<Uint8List> generateRentReceipt({
    required String tenantName,
    required String ownerName,
    required String propertyAddress,
    required double amount,
    required DateTime date,
    required String paymentMethod,
    required String receiptNumber,
    String? currencySymbol = '₹', // Default to INR
  }) async {
    final pdf = pw.Document();

    // Load a font if needed, otherwise use default
    final font = await PdfGoogleFonts.outfitRegular();
    final boldFont = await PdfGoogleFonts.outfitBold();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Container(
            padding: const pw.EdgeInsets.all(32),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                // Header
                pw.Center(
                  child: pw.Text(
                    'RENT RECEIPT',
                    style: pw.TextStyle(
                      font: boldFont,
                      fontSize: 24,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.blue800,
                    ),
                  ),
                ),
                pw.SizedBox(height: 32),

                // Receipt Details
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('Date: ${DateFormat('dd MMM yyyy').format(date)}', style: pw.TextStyle(font: font)),
                    pw.Text('Receipt #: $receiptNumber', style: pw.TextStyle(font: font, fontWeight: pw.FontWeight.bold)),
                  ],
                ),
                pw.Divider(color: PdfColors.grey300),
                pw.SizedBox(height: 20),

                // Content
                pw.RichText(
                  text: pw.TextSpan(
                    style: pw.TextStyle(font: font, fontSize: 14, lineSpacing: 6),
                    children: [
                      const pw.TextSpan(text: 'Received with thanks from '),
                      pw.TextSpan(text: tenantName, style: pw.TextStyle(font: boldFont)),
                      const pw.TextSpan(text: ',\n'),
                      
                      const pw.TextSpan(text: 'the sum of '),
                      pw.TextSpan(text: '$currencySymbol${amount.toStringAsFixed(2)}', style: pw.TextStyle(font: boldFont, fontSize: 16)),
                      const pw.TextSpan(text: ' paid via '),
                      pw.TextSpan(text: paymentMethod, style: pw.TextStyle(font: boldFont)),
                      const pw.TextSpan(text: '.'),
                    ],
                  ),
                ),
                pw.SizedBox(height: 20),
                
                pw.Text('For payment of rent at property:', style: pw.TextStyle(font: font, color: PdfColors.grey700)),
                pw.SizedBox(height: 4),
                pw.Text(propertyAddress, style: pw.TextStyle(font: boldFont, fontSize: 14)),
                
                pw.SizedBox(height: 40),

                // Footer / Signature Area
                 pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.end,
                  children: [
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.center,
                      children: [
                        pw.Container(
                          width: 150,
                          height: 1,
                          color: PdfColors.black,
                        ),
                        pw.SizedBox(height: 4),
                        pw.Text(ownerName, style: pw.TextStyle(font: boldFont)),
                        pw.Text('(Landlord)', style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey600)),
                      ],
                    ),
                  ],
                ),
                
                pw.Spacer(),
                pw.Divider(color: PdfColors.grey300),
                pw.Center(
                  child: pw.Text(
                    'Generated by KirayaBook Pro',
                    style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey500),
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );

    return pdf.save();
  }

  /// Generates a comprehensive Portfolio Audit Report PDF.
  Future<Uint8List> generateAuditReport({
    required String ownerName,
    required ReportsData data,
    required ReportRange range,
    String? currencySymbol = '₹',
  }) async {
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.outfitRegular();
    final boldFont = await PdfGoogleFonts.outfitBold();
    final now = DateTime.now();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (pw.Context context) {
          return [
            // Branded Header
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('PORTFOLIO AUDIT REPORT', style: pw.TextStyle(font: boldFont, fontSize: 20, color: PdfColors.blue900)),
                    pw.Text('Period: ${range.label}', style: pw.TextStyle(font: boldFont, fontSize: 12, color: PdfColors.blue700)),
                    pw.Text('Generated by KirayaBook Pro', style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey600)),
                  ],
                ),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    pw.Text(ownerName, style: pw.TextStyle(font: boldFont, fontSize: 12)),
                    pw.Text(DateFormat('dd MMMM yyyy').format(now), style: pw.TextStyle(font: font, fontSize: 10)),
                  ],
                ),
              ],
            ),
            pw.SizedBox(height: 30),

            // 1. Executive Summary
            pw.Text('EXECUTIVE SUMMARY', style: pw.TextStyle(font: boldFont, fontSize: 14, color: PdfColors.blue700)),
            pw.SizedBox(height: 10),
            pw.Container(
              padding: const pw.EdgeInsets.all(15),
              decoration: pw.BoxDecoration(
                color: PdfColors.grey100,
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  _buildPdfStat('Total Collected', '$currencySymbol${data.totalCollected}', boldFont, font, PdfColors.green700),
                  _buildPdfStat('Total Expenses', '$currencySymbol${data.totalExpenses}', boldFont, font, PdfColors.red700),
                  _buildPdfStat('Net Profit', '$currencySymbol${data.netProfit}', boldFont, font, PdfColors.blue700),
                ],
              ),
            ),
            pw.SizedBox(height: 30),

            // 2. Revenue Trend Table
            pw.Text('LAST 6 MONTHS PERFORMANCE', style: pw.TextStyle(font: boldFont, fontSize: 14, color: PdfColors.blue700)),
            pw.SizedBox(height: 10),
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                  children: [
                    _buildTableCell('Month', boldFont, isHeader: true),
                    _buildTableCell('Collected', boldFont, isHeader: true),
                    _buildTableCell('Pending', boldFont, isHeader: true),
                    _buildTableCell('Total Expected', boldFont, isHeader: true),
                  ],
                ),
                ...data.revenueTrend.map((s) => pw.TableRow(
                  children: [
                    _buildTableCell(s.monthLabel, font),
                    _buildTableCell('$currencySymbol${s.collected}', font),
                    _buildTableCell('$currencySymbol${s.pending}', font),
                    _buildTableCell('$currencySymbol${s.collected + s.pending}', font),
                  ],
                )),
              ],
            ),
            pw.SizedBox(height: 30),

            // 3. Occupancy Status
            pw.Text('PORTFOLIO HEALTH', style: pw.TextStyle(font: boldFont, fontSize: 14, color: PdfColors.blue700)),
            pw.SizedBox(height: 10),
            pw.Row(
              children: [
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Total Managed Units: ${data.totalUnits}', style: pw.TextStyle(font: font)),
                      pw.Text('Occupancy Rate: ${(data.totalUnits > 0 ? (data.occupiedUnits / data.totalUnits * 100) : 0).toStringAsFixed(1)}%', style: pw.TextStyle(font: boldFont)),
                    ],
                  ),
                ),
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Occupied: ${data.occupiedUnits}', style: pw.TextStyle(font: font, color: PdfColors.green700)),
                      pw.Text('Vacant: ${data.vacantUnits}', style: pw.TextStyle(font: font, color: PdfColors.red700)),
                    ],
                  ),
                ),
              ],
            ),
            pw.SizedBox(height: 30),

            // 4. Defaulters Alert
            if (data.topDefaulters.isNotEmpty) ...[
              pw.Text('TOP PENDING PAYMENTS', style: pw.TextStyle(font: boldFont, fontSize: 14, color: PdfColors.red700)),
              pw.SizedBox(height: 10),
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
                children: [
                  pw.TableRow(
                    decoration: const pw.BoxDecoration(color: PdfColors.red100),
                    children: [
                      _buildTableCell('Tenant Name', boldFont, isHeader: true),
                      _buildTableCell('Outstanding Amount', boldFont, isHeader: true),
                    ],
                  ),
                  ...data.topDefaulters.map((d) => pw.TableRow(
                    children: [
                      _buildTableCell(d.name, font),
                      _buildTableCell('$currencySymbol${d.amount}', font),
                    ],
                  )),
                ],
              ),
            ],
            
            pw.SizedBox(height: 40),
            pw.Divider(color: PdfColors.grey300),
            pw.Center(
               child: pw.Text('End of Official Audit Report', style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey500)),
            ),
          ];
        },
      ),
    );

    return pdf.save();
  }

  pw.Widget _buildPdfStat(String label, String value, pw.Font boldFont, pw.Font font, PdfColor color) {
    return pw.Column(
      children: [
        pw.Text(label, style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey700)),
        pw.SizedBox(height: 4),
        pw.Text(value, style: pw.TextStyle(font: boldFont, fontSize: 16, color: color)),
      ],
    );
  }

  pw.Widget _buildTableCell(String text, pw.Font font, {bool isHeader = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(text, style: pw.TextStyle(font: font, fontSize: isHeader ? 10 : 9)),
    );
  }
}
